### PR TITLE
evenly distribute views

### PR DESCRIPTION
**Pull request by dkk**
I created a new function spaceViews:onAxis:withMargin:, which lets you decide if you want margins or not. I also corrected spaceViews:onAxis:, since it was creating bigger margins at the sides (see http://stackoverflow.com/questions/28983492/space-evenly-across-a-view-without-margins).

Unfortunately I had to use spacer views to accomplish it. I also tried without, but failed miserably (you can take a look at version 999a20e).

Further, the robot example was extended to show the new functionality and the screenshot has been updated.

### CODE REVIEW

**Comment by jrturton** [comment]
The robot looks really evil now! I'll take a look at this, thanks very much

**Comment by jrturton** [comment]
I'm not going to merge this as it stands because:

- There are no unit tests for the added functionality
- I'm not crazy about spacer views being used if they're not necessary (the original method body should have been left as is)
- The code formatting doesn't match the rest of the repo
- You've used iOS8 only functionality (activateConstraints)
- The robot's new arm doesn't look right in the image - it's right next to the body
- You've left in some code which really shouldn't be there (setting the background colours to yellow for the spacer views??)

Thanks though. As for your original question you might have some luck with the container view approach, but pinning the outer edges of the first and last views to the main view, so the container "hangs outside" the main view - I hope that makes sense, I don't have a lot of time to look into this right now!

**Comment by dkk** [comment]
>There are no unit tests for the added functionality

Correct.. should be updated

>I'm not crazy about spacer views being used if they're not necessary (the original method body should have been left as is)

I'm not crazy about it either, but unfortunately the original method does not work as expected. The spaces at the borders were bigger than the spaces in between views, and I found no other way to overcome this issue. 

>The code formatting doesn't match the rest of the repo

I tried to make it as similar as possible, but you can change the formatting if you want.

>You've used iOS8 only functionality (activateConstraints)

I chose activateContraints over addConstraints since addConstraints is deprecated and has the comment "This method will be deprecated in a future release and should be avoided.  Instead use +[NSLayoutConstraint activateConstraints:]". You can just change the line "[NSLayoutConstraint activateConstraints:constraints];" to "[self addConstraint:constraint];", that would work too.

>The robot's new arm doesn't look right in the image - it's right next to the body

That's because it's not the arm, it was supposed to be part of the body (something like LEDs or a reflection? :) )

>You've left in some code which really shouldn't be there (setting the background colours to yellow for the spacer views??)

Sorry about that, it was test code, corrected at https://github.com/dkk/UIView-Autolayout

**Comment by dkk** [comment]
I also changed back activateConstraints: to addConstraints:, I just realized that it only works on iOS8+, I thought it was introduced earlier.

**Comment by jrturton** [comment]
If you add the new unit tests I'll take another look at reopening and merging this, thanks!

**Pull request closed without merging**
